// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpKafTd6Rd0sVw0p_eKrIkOfuVhgYS1IA',
    appId: '1:302850606035:web:d8926f4c599ba76fa2e526',
    messagingSenderId: '302850606035',
    projectId: 'qrcode-app-57dc6',
    authDomain: 'qrcode-app-57dc6.firebaseapp.com',
    storageBucket: 'qrcode-app-57dc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOevalixlUSgdZ7mrmO_-Bzb4g9HYM2dw',
    appId: '1:302850606035:android:0db69bdb7274b02ea2e526',
    messagingSenderId: '302850606035',
    projectId: 'qrcode-app-57dc6',
    storageBucket: 'qrcode-app-57dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA02kia7X64niQMO0GoDnR4R41GgoXxpk4',
    appId: '1:302850606035:ios:56becf2f832c88dea2e526',
    messagingSenderId: '302850606035',
    projectId: 'qrcode-app-57dc6',
    storageBucket: 'qrcode-app-57dc6.appspot.com',
    iosBundleId: 'com.example.qrCodeSttScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA02kia7X64niQMO0GoDnR4R41GgoXxpk4',
    appId: '1:302850606035:ios:47b01890bcfa9ea2a2e526',
    messagingSenderId: '302850606035',
    projectId: 'qrcode-app-57dc6',
    storageBucket: 'qrcode-app-57dc6.appspot.com',
    iosBundleId: 'com.example.qrCodeSttScanner.RunnerTests',
  );
}
